fixtures:
  repositories:
    stdlib:
      repo: git://github.com/puppetlabs/puppetlabs-stdlib.git
      ref: 4.2.2
    gcc:
      repo: git://github.com/puppetlabs/puppetlabs-gcc.git
      ref: 0.2.0
    git:
      repo: git://github.com/puppetlabs/puppetlabs-git.git
      ref: 0.1.0
  symlinks:
    devtools: "#{source_dir}"
