fixtures:
  repositories:
    stdlib:
      repo: git://github.com/puppetlabs/puppetlabs-stdlib.git
      ref: 4.1.0
    gcc:
      repo: git://github.com/puppetlabs/puppetlabs-gcc.git
      ref: 0.1.0
    git:
      repo: git://github.com/puppetlabs/puppetlabs-git.git
      ref: 0.0.3
  symlinks:
    devtools: "#{source_dir}"
