name   'leonardothibes-devtools'
author 'leonardothibes'
version '1.0.0'
license 'MIT'
summary 'A Puppet module that installs all necessary packages for compiling basic software.'
description 'A Puppet module that installs all necessary packages for compiling basic software.'
source 'git://github.com/leonardothibes/puppet-devtools.git'
project_page 'http://github.com/leonardothibes/puppet-devtools'
dependency 'puppetlabs/stdlib', '>=2.6.0'
dependency 'puppetlabs/git', '0.x'
dependency 'puppetlabs/gcc', '>=0.2.0'
dependency 'mhuffnagle/make', '0.x'
